// Code generated by go generate; DO NOT EDIT.
package router

import (
	"github.com/Alexandr-Fox/fox-core/internal/controllers"
	"github.com/gofiber/fiber/v2"
)

// RegisterRESTRoutes регистрирует REST-роуты для всех моделей
func RegisterRESTRoutes(app *fiber.App) {
	api := app.Group("/api")

	AppPing := func(c *fiber.Ctx) error {
		model := controllers.NewApp()
		if err := model.Ping(c); err != nil {
			return err.(error)
		}
		return c.SendStatus(fiber.StatusOK)
	}
	api.Get("/app.ping", AppPing)
	api.Post("/app.ping", AppPing)

	AppApiVersions := func(c *fiber.Ctx) error {
		model := controllers.NewApp()
		if err := model.ApiVersions(c); err != nil {
			return err.(error)
		}
		return c.SendStatus(fiber.StatusOK)
	}
	api.Get("/app.apiVersions", AppApiVersions)
	api.Post("/app.apiVersions", AppApiVersions)

	AppDocs := func(c *fiber.Ctx) error {
		model := controllers.NewApp()
		if err := model.Docs(c); err != nil {
			return err.(error)
		}
		return c.SendStatus(fiber.StatusOK)
	}
	api.Get("/app.docs", AppDocs)
	api.Post("/app.docs", AppDocs)

	AppMethods := func(c *fiber.Ctx) error {
		model := controllers.NewApp()
		if err := model.Methods(c); err != nil {
			return err.(error)
		}
		return c.SendStatus(fiber.StatusOK)
	}
	api.Get("/app.methods", AppMethods)
}
