// Code generated by go generate; DO NOT EDIT.
package models

import (
	"fmt"
	"github.com/Alexandr-Fox/fox-core/internal/database"
)

// Migrate запускает AutoMigrate для всех моделей
func Migrate() {
	cfg := database.ReadDatabaseConfig()

	database.GetCoreDB().Exec(fmt.Sprintf("CREATE SCHEMA IF NOT EXISTS %s", cfg.Schema))

	err := database.GetCoreDB().AutoMigrate(&Config{})
	if err != nil {
		panic(err)
	}
}
