// Code generated by go generate; DO NOT EDIT.
package controllers

import (
	"github.com/gofiber/fiber/v2"
)

// Methods регистрирует все REST-роуты для всех моделей
func (app *App) Methods(ctx *fiber.Ctx) error {
	return ctx.JSON([]string{
		"POST app.ping", "GET app.ping",
		"POST app.apiVersions", "GET app.apiVersions",
		"POST app.docs", "GET app.docs",
	})
}
